AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: visitor-tracking
Resources:
  VisitorTrackingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: visitor-request/
      Handler: app.handler
      Runtime: nodejs12.x
